# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in lapidario.gemspec
gemspec

gem "rake"

group :development, :test do
  gem "pry", require: true

  gem "rspec"

  gem "rubocop"
end
